"""Embedded, clean English word lists for Wend, keyed by length (3, 4, 5, 6).

No external files, no network, stdlib only. Common, family-friendly words.
The module-level check at the bottom guarantees every entry is exactly the
right length and purely alphabetic, so the generator can trust the lists.
"""

WORDS = {
    3: [
        "ACE", "ACT", "ADD", "AGE", "AID", "AIM", "AIR", "ANT", "APE", "ARC",
        "ARM", "ART", "ASH", "ASK", "BAG", "BAT", "BAY", "BED", "BEE", "BID",
        "BIG", "BIT", "BOW", "BOX", "BOY", "BUD", "BUG", "BUS", "BUY", "CAB",
        "CAN", "CAP", "CAR", "CAT", "COB", "COD", "COG", "COW", "COY", "CRY",
        "CUB", "CUP", "CUT", "DAM", "DAY", "DEN", "DEW", "DIG", "DIM", "DIP",
        "DOG", "DOT", "DRY", "DUE", "DUG", "EAR", "EAT", "EGG", "ELF", "ELK",
        "ELM", "END", "EYE", "FAN", "FAR", "FAT", "FEW", "FIG", "FIN", "FIT",
        "FIX", "FLY", "FOG", "FOX", "FRY", "FUN", "FUR", "GAP", "GAS", "GEM",
        "GET", "GUM", "GUN", "GUT", "GUY", "HAM", "HAT", "HAY", "HEN", "HIP",
        "HIT", "HOG", "HOP", "HOT", "HUB", "HUG", "HUT", "ICE", "ICY", "INK",
        "IVY", "JAM", "JAR", "JAW", "JAY", "JET", "JOB", "JOG", "JOY", "JUG",
        "KEY", "KID", "KIT", "LAB", "LAP", "LAW", "LEG", "LID", "LIP", "LOG",
        "LOT", "LOW", "MAD", "MAN", "MAP", "MAT", "MIX", "MOB", "MOP", "MUD",
        "MUG", "NAP", "NET", "NEW", "NOD", "NUT", "OAK", "OAR", "ODD", "OIL",
        "OLD", "ONE", "OWL", "OWN", "PAD", "PAN", "PAT", "PAW", "PEA", "PEG",
        "PEN", "PET", "PIE", "PIG", "PIN", "PIT", "POD", "POT", "PUP", "RAG",
        "RAM", "RAT", "RAW", "RAY", "RED", "RIB", "RIM", "RIP", "ROD", "ROW",
        "RUB", "RUG", "RUN", "SAD", "SAP", "SAT", "SAW", "SEA", "SET", "SIP",
        "SIT", "SIX", "SKY", "SLY", "SON", "SOW", "SPA", "SPY", "SUB", "SUN",
        "TAB", "TAG", "TAN", "TAP", "TAR", "TAX", "TEA", "TEN", "TIE", "TIN",
        "TIP", "TOE", "TON", "TOP", "TOW", "TOY", "TUB", "TUG", "URN", "USE",
        "VAN", "VAT", "VET", "VOW", "WAR", "WAX", "WAY", "WEB", "WED", "WET",
        "WIG", "WIN", "WIT", "YAK", "YAM", "YAP", "YES", "YET", "ZAP", "ZIP",
        "ZOO",
    ],
    4: [
        "ABLE", "ACID", "AGED", "AREA", "ARMY", "AUNT", "BABY", "BACK", "BAKE",
        "BALL", "BAND", "BANK", "BARN", "BASE", "BATH", "BEAD", "BEAM", "BEAN",
        "BEAR", "BEAT", "BELL", "BELT", "BEST", "BIKE", "BIRD", "BITE", "BLUE",
        "BOAT", "BODY", "BOLD", "BOLT", "BONE", "BOOK", "BOOT", "BORN", "BOTH",
        "BOWL", "BULL", "BUSH", "BUSY", "CAFE", "CAGE", "CAKE", "CALF", "CALL",
        "CALM", "CAMP", "CANE", "CARD", "CARE", "CART", "CASE", "CASH", "CAST",
        "CAVE", "CELL", "CHAT", "CHEF", "CHIN", "CHIP", "CITY", "CLAM", "CLAP",
        "CLAW", "CLAY", "CLIP", "CLUB", "CLUE", "COAL", "COAT", "CODE", "COIN",
        "COLD", "COLT", "COME", "COOK", "COOL", "COPE", "COPY", "CORD", "CORE",
        "CORN", "COST", "CROP", "CROW", "CUBE", "CURL", "DARE", "DARK", "DASH",
        "DATA", "DATE", "DAWN", "DEAL", "DEAR", "DECK", "DEED", "DEEP", "DEER",
        "DESK", "DIAL", "DICE", "DINE", "DIRT", "DISH", "DIVE", "DOCK", "DOME",
        "DONE", "DOOR", "DOSE", "DOVE", "DRAG", "DRAW", "DREW", "DROP", "DRUM",
        "DUCK", "DUNE", "DUSK", "DUST", "DUTY", "EACH", "EARN", "EASE", "EAST",
        "EASY", "EDGE", "FACE", "FACT", "FADE", "FAIL", "FAIR", "FALL", "FARM",
        "FAST", "FATE", "FEAR", "FEED", "FEEL", "FELL", "FELT", "FERN", "FILE",
        "FILL", "FILM", "FIND", "FINE", "FIRE", "FIRM", "FISH", "FIST", "FIVE",
        "FLAG", "FLAT", "FLEE", "FLEW", "FLIP", "FLOW", "FOAM", "FOLD", "FOND",
        "FOOD", "FOOL", "FOOT", "FORK", "FORM", "FOUR", "FROG", "FUEL", "FULL",
        "FUND", "GAIN", "GAME", "GATE", "GAVE", "GEAR", "GERM", "GIFT", "GIRL",
        "GIVE", "GLAD", "GLOW", "GOAL", "GOAT", "GOLD", "GOLF", "GONE", "GOOD",
        "GOWN", "GRAB", "GRAY", "GREW", "GRID", "GRIN", "GRIP", "GROW", "GULF",
        "HAIL", "HAIR", "HALF", "HALL", "HAND", "HANG", "HARD", "HARE", "HARM",
        "HAWK", "HEAD", "HEAL", "HEAP", "HEAR", "HEAT", "HELD", "HELP", "HERB",
        "HERD", "HERE", "HIDE", "HIGH", "HIKE", "HILL", "HINT", "HIVE", "HOLD",
        "HOLE", "HOME", "HOOD", "HOOK", "HOPE", "HORN", "HOSE", "HOST", "HOUR",
        "HUNT", "HURT", "IDEA", "IRON", "ISLE", "ITEM", "JADE", "JOKE", "JUMP",
        "JURY", "JUST", "KEEN", "KEEP", "KICK", "KIND", "KING", "KISS", "KITE",
        "KNEE", "KNIT", "KNOT", "KNOW", "LACE", "LACK", "LADY", "LAKE", "LAMB",
        "LAMP", "LAND", "LANE", "LAST", "LATE", "LAVA", "LAWN", "LEAD", "LEAF",
        "LEAN", "LEAP", "LEFT", "LEND", "LENS", "LESS", "LIFE", "LIFT", "LIKE",
        "LIME", "LINE", "LINK", "LION", "LIST", "LIVE", "LOAD", "LOAF", "LOAN",
        "LOCK", "LOFT", "LONG", "LOOK", "LOOP", "LORD", "LOSE", "LOST", "LOUD",
        "LOVE", "LUCK", "MAID", "MAIL", "MAIN", "MAKE", "MALE", "MALL", "MANE",
        "MANY", "MARK", "MASK", "MAST", "MATE", "MATH", "MEAL", "MEAN", "MEAT",
        "MEET", "MELT", "MEND", "MENU", "MICE", "MILD", "MILE", "MILK", "MILL",
        "MIND", "MINE", "MINT", "MIST", "MOLD", "MOLE", "MOOD", "MOON", "MORE",
        "MOSS", "MOST", "MOTH", "MOVE", "MUCH", "MULE", "MUST", "NAIL", "NAME",
        "NAVY", "NEAR", "NEAT", "NECK", "NEED", "NEST", "NEWS", "NEXT", "NICE",
        "NINE", "NODE", "NOON", "NOSE", "NOTE", "OATH", "OBEY", "ONCE", "ONLY",
        "OPEN", "OVAL", "OVEN", "PACE", "PACK", "PAGE", "PAID", "PAIL", "PAIN",
        "PAIR", "PALE", "PALM", "PARK", "PART", "PASS", "PAST", "PATH", "PAVE",
        "PEAK", "PEAR", "PEEL", "PICK", "PILE", "PINE", "PINK", "PIPE", "PLAN",
        "PLAY", "PLOT", "PLUG", "PLUM", "PLUS", "POEM", "POET", "POLE", "POLL",
        "POND", "PONY", "POOL", "POOR", "PORT", "POSE", "POST", "POUR", "PRAY",
        "PREY", "PULL", "PUMP", "PURE", "PUSH", "QUIT", "QUIZ", "RACE", "RACK",
        "RAFT", "RAGE", "RAIL", "RAIN", "RAKE", "RANK", "RARE", "RASH", "RATE",
        "READ", "REAL", "REAR", "REED", "REEF", "REIN", "RELY", "REST", "RICE",
        "RICH", "RIDE", "RING", "RIPE", "RISE", "RISK", "ROAD", "ROAM", "ROAR",
        "ROBE", "ROCK", "ROLE", "ROLL", "ROOF", "ROOM", "ROOT", "ROPE", "ROSE",
        "RUIN", "RULE", "RUSH", "RUST", "SAFE", "SAGE", "SAIL", "SALE", "SALT",
        "SAME", "SAND", "SAVE", "SEAL", "SEAM", "SEAT", "SEED", "SEEK", "SEEM",
        "SEEN", "SELF", "SELL", "SEND", "SHIP", "SHOE", "SHOP", "SHOT", "SHOW",
        "SHUT", "SICK", "SIDE", "SIGN", "SILK", "SING", "SINK", "SITE", "SIZE",
        "SKIN", "SKIP", "SLAB", "SLED", "SLIP", "SLOT", "SLOW", "SNAP", "SNOW",
        "SOAK", "SOAP", "SOFA", "SOFT", "SOIL", "SOLD", "SOLE", "SOME", "SONG",
        "SOON", "SORT", "SOUL", "SOUP", "SOUR", "SPAN", "SPIN", "SPOT", "STAR",
        "STAY", "STEM", "STEP", "STIR", "STOP", "SUCH", "SUIT", "SUNG", "SUNK",
        "SURE", "SWAM", "SWAN", "SWAP", "SWAY", "SWIM", "TAIL", "TAKE", "TALE",
        "TALK", "TALL", "TAME", "TANK", "TAPE", "TASK", "TEAM", "TEAR", "TELL",
        "TEND", "TENT", "TERM", "TEST", "TEXT", "THAN", "THAT", "THEM", "THEN",
        "THIN", "THIS", "TIDE", "TIDY", "TILE", "TIME", "TINY", "TIRE", "TOAD",
        "TOLD", "TOLL", "TOMB", "TONE", "TOOL", "TORN", "TOUR", "TOWN", "TRAP",
        "TRAY", "TREE", "TRIM", "TRIP", "TRUE", "TUBE", "TUNA", "TUNE", "TURN",
        "TWIN", "TYPE", "UGLY", "UNIT", "UPON", "URGE", "USED", "VAIN", "VASE",
        "VAST", "VEIL", "VEIN", "VERY", "VEST", "VIEW", "VINE", "VOTE", "WADE",
        "WAGE", "WAIT", "WAKE", "WALK", "WALL", "WAND", "WANT", "WARM", "WARN",
        "WASH", "WASP", "WAVE", "WEAK", "WEAR", "WEED", "WEEK", "WELL", "WENT",
        "WEPT", "WEST", "WHAT", "WHEN", "WHIP", "WICK", "WIDE", "WIFE", "WILD",
        "WILL", "WIND", "WINE", "WING", "WINK", "WIPE", "WIRE", "WISE", "WISH",
        "WOLF", "WOOD", "WOOL", "WORD", "WORE", "WORK", "WORM", "YARD", "YARN",
        "YEAR", "YELL", "ZERO", "ZONE", "ZOOM",
    ],
    5: [
        "ABOUT", "ABOVE", "ACORN", "ACTOR", "ACUTE", "ADOPT", "ADULT", "AGENT",
        "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIKE", "ALIVE", "ALLOW",
        "ALONE", "ALONG", "ALTAR", "AMBER", "AMEND", "AMONG", "ANGEL", "ANGER",
        "ANGLE", "ANGRY", "ANKLE", "APART", "APPLE", "APPLY", "APRON", "ARENA",
        "ARGUE", "ARISE", "ARRAY", "ARROW", "ASIDE", "ASSET", "AUDIO", "AVOID",
        "AWAKE", "AWARD", "AWARE", "BACON", "BADGE", "BAGEL", "BAKER", "BASIC",
        "BASIL", "BASIN", "BATCH", "BEACH", "BEARD", "BEAST", "BEGAN", "BEGIN",
        "BEGUN", "BEING", "BELLY", "BELOW", "BENCH", "BERRY", "BIRTH", "BLACK",
        "BLADE", "BLAME", "BLANK", "BLAST", "BLAZE", "BLEND", "BLESS", "BLIND",
        "BLINK", "BLISS", "BLOCK", "BLOOM", "BLOWN", "BLUFF", "BLUSH", "BOARD",
        "BOAST", "BONUS", "BOOST", "BOOTH", "BOUND", "BOXER", "BRACE", "BRAID",
        "BRAIN", "BRAKE", "BRAND", "BRAVE", "BREAD", "BREAK", "BREED", "BRICK",
        "BRIDE", "BRIEF", "BRING", "BRISK", "BROAD", "BROIL", "BROKE", "BROOK",
        "BROOM", "BROWN", "BRUSH", "BUILD", "BUILT", "BUNCH", "BURNT", "BURST",
        "BUYER", "CABIN", "CABLE", "CAMEL", "CANAL", "CANDY", "CANOE", "CARGO",
        "CARRY", "CARVE", "CATCH", "CAUSE", "CEASE", "CHAIN", "CHAIR", "CHALK",
        "CHARM", "CHART", "CHASE", "CHEAP", "CHEAT", "CHECK", "CHEEK", "CHEER",
        "CHESS", "CHEST", "CHICK", "CHIEF", "CHILD", "CHILL", "CHIME", "CHIRP",
        "CHOIR", "CHOSE", "CHUNK", "CIDER", "CIGAR", "CIVIC", "CIVIL", "CLAIM",
        "CLAMP", "CLASH", "CLASS", "CLEAN", "CLEAR", "CLERK", "CLICK", "CLIFF",
        "CLIMB", "CLOAK", "CLOCK", "CLOSE", "CLOTH", "CLOUD", "CLOWN", "COACH",
        "COAST", "COBRA", "COLON", "COLOR", "COMET", "COMIC", "CORAL", "COUCH",
        "COUGH", "COULD", "COUNT", "COURT", "COVER", "CRAFT", "CRANE", "CRASH",
        "CRAWL", "CRAZY", "CREAM", "CREEK", "CREEP", "CREST", "CRISP", "CROSS",
        "CROWD", "CROWN", "CRUEL", "CRUMB", "CRUSH", "CRUST", "CURLY", "CURVE",
        "CYCLE", "DAILY", "DAIRY", "DAISY", "DANCE", "DANDY", "DEALT", "DEBUT",
        "DECAY", "DELAY", "DELTA", "DENSE", "DEPTH", "DERBY", "DIARY", "DITCH",
        "DIVER", "DIZZY", "DOUGH", "DOZEN", "DRAFT", "DRAIN", "DRAMA", "DRANK",
        "DRAWN", "DREAM", "DRESS", "DRIED", "DRIFT", "DRILL", "DRINK", "DRIVE",
        "DROVE", "DROWN", "DRUNK", "DWELL", "EAGER", "EAGLE", "EARLY", "EARTH",
        "EIGHT", "ELBOW", "ELDER", "ELECT", "ELITE", "EMPTY", "ENJOY", "ENTER",
        "ENTRY", "EQUAL", "ERASE", "ERROR", "ESSAY", "EVENT", "EVERY", "EXACT",
        "EXCEL", "EXIST", "EXTRA", "FABLE", "FAINT", "FAITH", "FALSE", "FANCY",
        "FAULT", "FEAST", "FENCE", "FERRY", "FEVER", "FEWER", "FIBER", "FIELD",
        "FIERY", "FIFTY", "FIGHT", "FINAL", "FINCH", "FIRST", "FLAME", "FLASH",
        "FLEET", "FLESH", "FLING", "FLINT", "FLOAT", "FLOCK", "FLOOD", "FLOOR",
        "FLOUR", "FLUID", "FLUSH", "FLUTE", "FOCUS", "FORCE", "FORGE", "FORTH",
        "FOUND", "FRAME", "FRANK", "FRAUD", "FRESH", "FRIED", "FROST", "FROWN",
        "FRUIT", "FUDGE", "FULLY", "FUNNY", "GAUGE", "GHOST", "GIANT", "GIVEN",
        "GLAND", "GLARE", "GLASS", "GLEAM", "GLIDE", "GLOBE", "GLORY", "GLOVE",
        "GOING", "GOOSE", "GRACE", "GRADE", "GRAIN", "GRAND", "GRANT", "GRAPE",
        "GRAPH", "GRASP", "GRASS", "GRAVE", "GRAZE", "GREAT", "GREEN", "GREET",
        "GRILL", "GROIN", "GROOM", "GROSS", "GROUP", "GROVE", "GROWN", "GUARD",
        "GUESS", "GUEST", "GUIDE", "GUILT", "HABIT", "HANDY", "HAPPY", "HARSH",
        "HASTE", "HATCH", "HAVEN", "HEART", "HEAVY", "HEDGE", "HELLO", "HENCE",
        "HILLY", "HINGE", "HOBBY", "HONEY", "HONOR", "HORSE", "HOTEL", "HOUND",
        "HOUSE", "HOVER", "HUMAN", "HUMID", "HUMOR", "HURRY", "ICING", "IDEAL",
        "IMAGE", "INDEX", "INNER", "INPUT", "IVORY", "JEANS", "JELLY", "JEWEL",
        "JOINT", "JOLLY", "JUDGE", "JUICE", "JUICY", "KNEEL", "KNIFE", "KNOCK",
        "LABEL", "LABOR", "LARGE", "LASER", "LATCH", "LATER", "LAUGH", "LAYER",
        "LEARN", "LEASE", "LEAST", "LEAVE", "LEDGE", "LEMON", "LEVEL", "LIGHT",
        "LIMIT", "LINEN", "LIVER", "LLAMA", "LOBBY", "LOCAL", "LODGE", "LOGIC",
        "LOOSE", "LORRY", "LOVER", "LOWER", "LOYAL", "LUCKY", "LUNAR", "LUNCH",
        "LYRIC", "MAGIC", "MAJOR", "MAKER", "MANGO", "MAPLE", "MARCH", "MARRY",
        "MATCH", "MAYBE", "MAYOR", "MEANT", "MEDAL", "MELON", "MERCY", "MERIT",
        "MERRY", "METAL", "METER", "MIGHT", "MINOR", "MINUS", "MIXED", "MODEL",
        "MOIST", "MONEY", "MONTH", "MOOSE", "MORAL", "MOTOR", "MOTTO", "MOUNT",
        "MOUSE", "MOUTH", "MOVIE", "MOWER", "MUDDY", "MUSIC", "NAKED", "NASTY",
        "NAVAL", "NERVE", "NEVER", "NEWLY", "NIGHT", "NINTH", "NOBLE", "NOISE",
        "NORTH", "NOVEL", "NURSE", "NYLON", "OCEAN", "OFFER", "OFTEN", "OLIVE",
        "ONION", "ORBIT", "ORDER", "ORGAN", "OTTER", "OUGHT", "OUNCE", "OWNER",
        "PAINT", "PANDA", "PANEL", "PANIC", "PAPER", "PARTY", "PASTA", "PASTE",
        "PATCH", "PAUSE", "PEACE", "PEACH", "PEARL", "PEDAL", "PENNY", "PERCH",
        "PHASE", "PHONE", "PHOTO", "PIANO", "PILOT", "PINCH", "PITCH", "PIZZA",
        "PLACE", "PLAIN", "PLANE", "PLANK", "PLANT", "PLATE", "PLAZA", "PLEAD",
        "PLUCK", "POINT", "POLAR", "PORCH", "POUND", "POWER", "PRESS", "PRICE",
        "PRIDE", "PRIME", "PRINT", "PRIOR", "PRIZE", "PROBE", "PROOF", "PROUD",
        "PROVE", "PROWL", "PULSE", "PUNCH", "PUPPY", "QUACK", "QUAKE", "QUART",
        "QUEEN", "QUERY", "QUEST", "QUICK", "QUIET", "QUILT", "QUOTE", "RADAR",
        "RADIO", "RAISE", "RALLY", "RANCH", "RANGE", "RAPID", "RATIO", "REACH",
        "READY", "REALM", "REBEL", "REFER", "REIGN", "RELAX", "REPAY", "REPLY",
        "RESET", "RHYME", "RIDER", "RIDGE", "RIFLE", "RIGHT", "RINSE", "RIVAL",
        "RIVER", "ROAST", "ROBIN", "ROBOT", "ROCKY", "ROGUE", "ROUGH", "ROUND",
        "ROUTE", "ROYAL", "RUGBY", "RULER", "RURAL", "SADLY", "SAINT", "SALAD",
        "SALON", "SANDY", "SAUCE", "SCALE", "SCARF", "SCENE", "SCENT", "SCOLD",
        "SCONE", "SCOOP", "SCOPE", "SCORE", "SCOUT", "SCRAP", "SCREW", "SCRUB",
        "SEIZE", "SENSE", "SERVE", "SETUP", "SEVEN", "SHACK", "SHADE", "SHAKE",
        "SHAKY", "SHALL", "SHAME", "SHAPE", "SHARE", "SHARK", "SHARP", "SHAVE",
        "SHEEP", "SHEET", "SHELF", "SHELL", "SHIFT", "SHINE", "SHINY", "SHIRT",
        "SHOCK", "SHONE", "SHOOK", "SHOOT", "SHORE", "SHORT", "SHOUT", "SHOWN",
        "SHRUB", "SHRUG", "SIEGE", "SIGHT", "SILLY", "SIXTH", "SIXTY", "SKATE",
        "SKILL", "SKULL", "SLASH", "SLATE", "SLEEP", "SLEET", "SLICE", "SLIDE",
        "SLIME", "SLING", "SLOPE", "SLOTH", "SMALL", "SMART", "SMASH", "SMELL",
        "SMILE", "SMOKE", "SNACK", "SNAIL", "SNAKE", "SNEAK", "SNIFF", "SNORE",
        "SNOWY", "SOLAR", "SOLID", "SOLVE", "SORRY", "SOUND", "SOUTH", "SPACE",
        "SPADE", "SPARE", "SPARK", "SPEAK", "SPEAR", "SPEED", "SPELL", "SPEND",
        "SPICE", "SPICY", "SPILL", "SPINE", "SPLIT", "SPOIL", "SPOKE", "SPOON",
        "SPORT", "SPRAY", "SQUAD", "STACK", "STAFF", "STAGE", "STAIN", "STAIR",
        "STAKE", "STALE", "STALK", "STALL", "STAMP", "STAND", "STARE", "START",
        "STATE", "STEAK", "STEAL", "STEAM", "STEEL", "STEEP", "STEER", "STICK",
        "STIFF", "STILL", "STING", "STINK", "STOCK", "STOMP", "STONE", "STOOD",
        "STOOL", "STORE", "STORM", "STORY", "STOVE", "STRAP", "STRAW", "STRAY",
        "STRIP", "STUCK", "STUDY", "STUFF", "STUMP", "STUNG", "STYLE", "SUGAR",
        "SUNNY", "SUPER", "SURGE", "SWEAT", "SWEEP", "SWEET", "SWELL", "SWEPT",
        "SWIFT", "SWING", "SWORD", "SWORE", "SWORN", "SYRUP", "TABLE", "TAKEN",
        "TASTE", "TASTY", "TEACH", "TEASE", "TEETH", "TEMPO", "TENSE", "TENTH",
        "THANK", "THEFT", "THEIR", "THEME", "THERE", "THESE", "THICK", "THIEF",
        "THING", "THINK", "THIRD", "THORN", "THOSE", "THREE", "THREW", "THROB",
        "THROW", "THUMB", "TIGER", "TIGHT", "TIMER", "TITLE", "TOAST", "TODAY",
        "TOKEN", "TOOTH", "TOPIC", "TORCH", "TOTAL", "TOUCH", "TOUGH", "TOWEL",
        "TOWER", "TOXIC", "TRACE", "TRACK", "TRADE", "TRAIL", "TRAIN", "TRAMP",
        "TRASH", "TREAT", "TREND", "TRIAL", "TRIBE", "TRICK", "TRIED", "TROOP",
        "TROUT", "TRUCK", "TRULY", "TRUNK", "TRUST", "TRUTH", "TULIP", "TUNIC",
        "TWEED", "TWICE", "TWINE", "TWIST", "ULTRA", "UNCLE", "UNDER", "UNION",
        "UNITE", "UNTIL", "UPPER", "UPSET", "URBAN", "USAGE", "USUAL", "VAGUE",
        "VALID", "VALUE", "VALVE", "VAPOR", "VAULT", "VENUE", "VERSE", "VIDEO",
        "VILLA", "VINYL", "VIRUS", "VISIT", "VITAL", "VIVID", "VOCAL", "VOICE",
        "VOWEL", "WAGON", "WAIST", "WAIVE", "WASTE", "WATCH", "WATER", "WEARY",
        "WEAVE", "WEDGE", "WEIGH", "WEIRD", "WHALE", "WHEAT", "WHEEL", "WHERE",
        "WHICH", "WHILE", "WHINE", "WHIRL", "WHISK", "WHITE", "WHOLE", "WHOSE",
        "WIDEN", "WIDOW", "WIDTH", "WINCE", "WITCH", "WOMAN", "WOMEN", "WORLD",
        "WORRY", "WORSE", "WORST", "WORTH", "WOULD", "WOUND", "WOVEN", "WRECK",
        "WRIST", "WRITE", "WRONG", "WROTE", "YACHT", "YEARN", "YEAST", "YIELD",
        "YOUNG", "YOUTH", "ZEBRA", "ZESTY",
    ],
    6: [
        "ABSORB", "ACCEPT", "ACCESS", "ACCUSE", "ACROSS", "ACTION", "ACTIVE",
        "ACTUAL", "ADVICE", "ADVISE", "AFFAIR", "AFFECT", "AFFORD", "AFRAID",
        "AGENCY", "AGREED", "ALMOND", "ALMOST", "ALWAYS", "AMOUNT", "ANCHOR",
        "ANIMAL", "ANNUAL", "ANSWER", "ANTLER", "ANYONE", "ANYWAY", "APPEAL",
        "APPEAR", "AROUND", "ARRIVE", "ARTIST", "ASLEEP", "ASSIST", "ASSUME",
        "ASSURE", "ATTACH", "ATTACK", "ATTEND", "AUTHOR", "AUTUMN", "AVENUE",
        "BAKERY", "BALLET", "BALLOT", "BAMBOO", "BANANA", "BANDIT", "BANNER",
        "BARREL", "BASKET", "BATTLE", "BEACON", "BEAUTY", "BEAVER", "BECAME",
        "BECOME", "BEFORE", "BEHALF", "BEHAVE", "BEHIND", "BELIEF", "BELONG",
        "BESIDE", "BETRAY", "BETTER", "BEYOND", "BISHOP", "BITTEN", "BITTER",
        "BLONDE", "BOTHER", "BOTTLE", "BOTTOM", "BOUNCE", "BRANCH", "BRANDY",
        "BREACH", "BREATH", "BREEZE", "BRIDGE", "BRIGHT", "BROKEN", "BRONZE",
        "BROWSE", "BRUNCH", "BUBBLE", "BUCKET", "BUCKLE", "BUDGET", "BUFFET",
        "BUNDLE", "BUNKER", "BURDEN", "BUREAU", "BUTTER", "BUTTON", "CACTUS",
        "CAMERA", "CAMPER", "CANCEL", "CANDLE", "CANNON", "CANYON", "CARBON",
        "CAREER", "CARPET", "CARROT", "CARTON", "CASHEW", "CASINO", "CASTLE",
        "CASUAL", "CATTLE", "CAUGHT", "CAVERN", "CELERY", "CELLAR", "CEMENT",
        "CENSUS", "CENTER", "CENTRE", "CEREAL", "CHANCE", "CHANGE", "CHAPEL",
        "CHARGE", "CHEESE", "CHERRY", "CHOICE", "CHOOSE", "CHOSEN", "CHROME",
        "CIRCLE", "CIRCUS", "CITRUS", "CLAMOR", "CLASSY", "CLEVER", "CLIENT",
        "CLIMAX", "CLOSET", "CLOVER", "CLUTCH", "COBALT", "COFFEE", "COLLAR",
        "COLONY", "COLUMN", "COMBAT", "COMEDY", "COMMON", "COOKIE", "COOLER",
        "COPPER", "CORNER", "CORRAL", "COSMIC", "COTTON", "COUGAR", "COUPLE",
        "COUPON", "COURSE", "COUSIN", "COWBOY", "CRADLE", "CRAYON", "CREATE",
        "CREDIT", "CRISPY", "CRUISE", "CRUNCH", "CUCKOO", "CUDDLE", "CURFEW",
        "CURSOR", "CUSTOM", "CYMBAL", "DAGGER", "DAINTY", "DAMAGE", "DANCER",
        "DANGER", "DAPPER", "DARING", "DAZZLE", "DEALER", "DEBATE", "DECADE",
        "DECENT", "DECIDE", "DECODE", "DEFEAT", "DEFEND", "DEFINE", "DEGREE",
        "DELETE", "DELUXE", "DEMAND", "DENIAL", "DENOTE", "DENTAL", "DEPART",
        "DEPEND", "DEPICT", "DEPLOY", "DEPUTY", "DESERT", "DESIGN", "DESIRE",
        "DETAIL", "DETECT", "DEVICE", "DEVOTE", "DIESEL", "DIGEST", "DINGHY",
        "DINNER", "DIRECT", "DISARM", "DIVIDE", "DOCTOR", "DOLLAR", "DONKEY",
        "DOODLE", "DOUBLE", "DRAGON", "DRAPER", "DREARY", "DRIVEN", "DRIVER",
        "DUPLEX", "DURESS", "DURING", "EARNED", "EASILY", "EATING", "ECHOES",
        "EDITOR", "EFFECT", "EFFORT", "EIGHTH", "EITHER", "ELEVEN", "EMBARK",
        "EMBLEM", "EMPIRE", "EMPLOY", "ENABLE", "ENAMEL", "ENDURE", "ENERGY",
        "ENGAGE", "ENGINE", "ENIGMA", "ENOUGH", "ENSURE", "ENTIRE", "ENTITY",
        "ERRAND", "ESCAPE", "ESTATE", "ETCHED", "ETHNIC", "EVOLVE", "EXCEED",
        "EXCEPT", "EXCESS", "EXCITE", "EXCUSE", "EXEMPT", "EXOTIC", "EXPAND",
        "EXPECT", "EXPERT", "EXPORT", "EXPOSE", "EXTEND", "EXTENT", "FABRIC",
        "FACADE", "FACIAL", "FACTOR", "FAIRLY", "FALCON", "FAMILY", "FAMINE",
        "FAMOUS", "FARMER", "FASTEN", "FATHER", "FAULTY", "FEEBLE", "FELLOW",
        "FEMALE", "FENDER", "FIASCO", "FIERCE", "FIGURE", "FILTER", "FINALE",
        "FINDER", "FINEST", "FINISH", "FIRMLY", "FISCAL", "FITTED", "FLAGON",
        "FLANGE", "FLASHY", "FLAVOR", "FLEECE", "FLIGHT", "FLINCH", "FLORAL",
        "FLOWER", "FLUENT", "FLURRY", "FOLDER", "FOLLOW", "FONDLY", "FOREST",
        "FORGET", "FORGOT", "FORMAL", "FORMAT", "FORMER", "FOSTER", "FOUGHT",
        "FOURTH", "FRAMED", "FREELY", "FRENZY", "FRIDGE", "FRIEND", "FRIGID",
        "FRINGE", "FRISKY", "FRIZZY", "FROSTY", "FROZEN", "FUMBLE", "FUNGUS",
        "FUNNEL", "FUSION", "GADGET", "GALAXY", "GALLON", "GALLOP", "GAMBLE",
        "GARAGE", "GARDEN", "GARLIC", "GARNET", "GATHER", "GENIUS", "GENTLE",
        "GENTLY", "GERBIL", "GEYSER", "GIGGLE", "GINGER", "GLANCE", "GLASSY",
        "GLIDER", "GLOBAL", "GLOSSY", "GOBBLE", "GOBLET", "GOBLIN", "GOLDEN",
        "GOSPEL", "GOSSIP", "GOVERN", "GRAVEL", "GREASE", "GREEDY", "GRILLE",
        "GROCER", "GROOVE", "GROTTO", "GROUND", "GROUSE", "GROVEL", "GROWTH",
        "GRUBBY", "GRUMPY", "GUITAR", "GUTTER", "HALLOW", "HAMLET", "HAMMER",
        "HAMPER", "HANDLE", "HANGAR", "HAPPEN", "HARBOR", "HARDLY", "HARROW",
        "HAZARD", "HEALTH", "HEARTH", "HEARTY", "HEATED", "HEATER", "HEAVEN",
        "HEDGES", "HEIGHT", "HELMET", "HELPER", "HERBAL", "HEREBY", "HERMIT",
        "HEROIC", "HIATUS", "HICCUP", "HIDDEN", "HIGHLY", "HINDER", "HITHER",
        "HOCKEY", "HOLDER", "HOLLOW", "HOMAGE", "HONEST", "HONORS", "HOODIE",
        "HORROR", "HORNET", "HOSTEL", "HUDDLE", "HUMANE", "HUMBLE", "HUMBLY",
        "HUNGRY", "HUNTER", "HURDLE", "HURRAY", "HYBRID", "HYMNAL", "ICICLE",
        "IGNORE", "IMPACT", "IMPART", "IMPORT", "IMPOSE", "INDENT", "INDIGO",
        "INDOOR", "INDUCE", "INFANT", "INFECT", "INFORM", "INHALE", "INJURE",
        "INJURY", "INLAND", "INMATE", "INNATE", "INSANE", "INSECT", "INSERT",
        "INSIDE", "INSIST", "INTACT", "INTEND", "INTENT", "INVADE", "INVENT",
        "INVEST", "INVITE", "INWARD", "ISLAND", "ITSELF", "JACKET", "JAGGED",
        "JAGUAR", "JERSEY", "JIGGLE", "JIGSAW", "JOCKEY", "JOSTLE", "JOVIAL",
        "JUGGLE", "JUMBLE", "JUMPER", "JUNGLE", "JUNIOR", "KENNEL", "KERNEL",
        "KETTLE", "KIDNEY", "KIMONO", "KINDLE", "KINDLY", "KINGLY", "KISSED",
        "KITTEN", "KNIGHT", "LADDER", "LADIES", "LAGOON", "LAPTOP", "LARGER",
        "LARVAE", "LATELY", "LATEST", "LATTER", "LAUNCH", "LAUREL", "LAWFUL",
        "LAWYER", "LAYOUT", "LEADER", "LEAGUE", "LEANED", "LEAPED", "LEARNT",
        "LEASED", "LEDGER", "LEGACY", "LEGEND", "LEMONS", "LENDER", "LENGTH",
        "LENTIL", "LESSEN", "LESSON", "LETTER", "LIABLE", "LIKELY", "LILIES",
        "LIMBER", "LINDEN", "LINEAR", "LINGER", "LIQUID", "LIQUOR", "LISTEN",
        "LITTLE", "LIVELY", "LIVING", "LIZARD", "LOADER", "LOAVES", "LOCALE",
        "LOCATE", "LOCKER", "LOCKET", "LOCUST", "LODGER", "LONELY", "LONGER",
        "LOOSEN", "LOTION", "LOUDLY", "LOUNGE", "LOVELY", "LOWEST", "LUMBER",
        "LUXURY", "MADDEN", "MAGNET", "MAIDEN", "MAINLY", "MAKEUP", "MALLET",
        "MAMMAL", "MANAGE", "MANNER", "MANTLE", "MARBLE", "MARGIN", "MARINE",
        "MARKED", "MARKER", "MARKET", "MARLIN", "MARMOT", "MARROW", "MARTIN",
        "MARVEL", "MASCOT", "MASTER", "MATTER", "MATURE", "MEADOW", "MEDDLE",
        "MEDIAN", "MEDLEY", "MELLOW", "MELODY", "MELONS", "MEMBER", "MEMOIR",
        "MEMORY", "MENACE", "MENTAL", "MENTOR", "MERELY", "MERGER", "METEOR",
        "METHOD", "METRIC", "MIDDAY", "MIDDLE", "MIGHTY", "MILDER", "MILKED",
        "MINGLE", "MINNOW", "MINUTE", "MIRROR", "MISERY", "MITTEN", "MOBILE",
        "MODEST", "MODULE", "MOMENT", "MONKEY", "MOSAIC", "MOTHER", "MOTIVE",
        "MOTTLE", "MUFFIN", "MULLET", "MUMBLE", "MURMUR", "MUSCLE", "MUSEUM",
        "MUSTER", "MUTTER", "MUTUAL", "MYRTLE", "MYSELF", "NAPKIN", "NARROW",
        "NATIVE", "NATURE", "NEARBY", "NEARLY", "NEATLY", "NECTAR", "NEEDLE",
        "NEPHEW", "NESTLE", "NETTLE", "NEURAL", "NEWEST", "NIBBLE", "NICELY",
        "NICKEL", "NIGHTS", "NIMBLE", "NOBODY", "NORMAL", "NOTICE", "NOTIFY",
        "NOTION", "NOUGAT", "NOZZLE", "NUGGET", "NUMBER", "NURSED", "NUTMEG",
        "OBLIGE", "OBTAIN", "OCELOT", "OFFEND", "OFFICE", "OFFSET", "OMELET",
        "ONWARD", "OPENLY", "OPTION", "ORANGE", "ORCHID", "ORDEAL", "ORDERS",
        "ORGANS", "ORIGIN", "ORIOLE", "ORNATE", "ORPHAN", "OSPREY", "OTTERS",
        "OUNCES", "OUTAGE", "OUTFIT", "OUTING", "OUTLAW", "OUTLET", "OUTRUN",
        "OYSTER", "PACKED", "PACKET", "PADDLE", "PALACE", "PANDAS", "PANTRY",
        "PARADE", "PARCEL", "PARDON", "PARENT", "PARLOR", "PARROT", "PARTLY",
        "PASTEL", "PASTRY", "PATCHY", "PATENT", "PATROL", "PATTER", "PAUPER",
        "PAUSED", "PEANUT", "PEBBLE", "PEDDLE", "PENCIL", "PEOPLE", "PEPPER",
        "PERMIT", "PERSON", "PETALS", "PETITE", "PETROL", "PEWTER", "PHRASE",
        "PICKLE", "PICNIC", "PIGEON", "PILLAR", "PILLOW", "PINION", "PIRATE",
        "PISTOL", "PLACID", "PLANET", "PLAQUE", "PLASMA", "PLATED", "PLAYER",
        "PLEASE", "PLEDGE", "PLENTY", "PLIGHT", "PLUCKY", "PLUNGE", "POCKET",
        "POETRY", "POINTS", "POISON", "POLICE", "POLISH", "POLITE", "PONDER",
        "PONIES", "POODLE", "PORTAL", "POSTER", "POTATO", "POTTER", "POWDER",
        "PRAISE", "PRANCE", "PRAYER", "PREACH", "PRETTY", "PRINCE", "PRISON",
        "PROFIT", "PROMPT", "PROPER", "PROTON", "PROVEN", "PUBLIC", "PUDDLE",
        "PUFFIN", "PULLEY", "PUNISH", "PUPPET", "PURPLE", "PURSUE", "PUZZLE",
        "PYTHON", "QUAINT", "QUARTZ", "QUEASY", "QUEENS", "QUENCH", "QUIVER",
        "QUOTED", "RABBIT", "RACING", "RACKET", "RADISH", "RAGGED", "RAISIN",
        "RANDOM", "RANGER", "RANSOM", "RAPIER", "RARELY", "RASCAL", "RATTLE",
        "RAVINE", "REALLY", "REALMS", "REAPER", "REASON", "REBORN", "RECALL",
        "RECENT", "RECESS", "RECIPE", "RECORD", "REDEEM", "REDUCE", "REFINE",
        "REFORM", "REFUND", "REFUSE", "REGARD", "REGION", "REGRET", "REJECT",
        "RELATE", "RELISH", "RELIVE", "RELOAD", "REMAIN", "REMARK", "REMEDY",
        "REMIND", "REMOTE", "REMOVE", "RENDER", "RENTAL", "REPAIR", "REPEAL",
        "REPEAT", "REPLAY", "REPORT", "RESALE", "RESCUE", "RESIDE", "RESIST",
        "RESORT", "RESULT", "RESUME", "RETAIL", "RETAIN", "RETIRE", "RETURN",
        "REVEAL", "REVERE", "REVISE", "REVIVE", "REWARD", "REWIND", "RHYTHM",
        "RIBBON", "RIDDLE", "RIGGED", "RIGHTS", "RIPPLE", "RISING", "RITUAL",
        "ROBUST", "ROCKET", "ROOKIE", "ROSTER", "ROTATE", "ROTTEN", "ROVING",
        "RUBBER", "RUBBLE", "RUBRIC", "RUDDER", "RUFFLE", "RUGGED", "RULING",
        "RUMBLE", "RUNNER", "RUSTIC", "SADDLE", "SAFARI", "SAFELY", "SAFETY",
        "SAILED", "SAILOR", "SALARY", "SALMON", "SALOON", "SALUTE", "SAMPLE",
        "SANDAL", "SATURN", "SAUCER", "SAVAGE", "SAVING", "SAVIOR", "SAVORY",
        "SCARCE", "SCHEME", "SCHOOL", "SCONES", "SCORCH", "SCRAPE", "SCREEN",
        "SCRIPT", "SCROLL", "SEALED", "SEARCH", "SEASON", "SECOND", "SECRET",
        "SECTOR", "SECURE", "SEEDED", "SEEKER", "SEESAW", "SEIZED", "SELDOM",
        "SELECT", "SELLER", "SENATE", "SENIOR", "SENSOR", "SERENE", "SERIAL",
        "SERVED", "SESAME", "SETTLE", "SEVERE", "SEWAGE", "SHABBY", "SHADOW",
        "SHAKEN", "SHAPED", "SHARED", "SHEATH", "SHERRY", "SHIELD", "SHIVER",
        "SHOULD", "SHOVEL", "SHOWER", "SHRANK", "SHREWD", "SHRIEK", "SHRIMP",
        "SHRINE", "SHRINK", "SHROUD", "SHRUNK", "SILVER", "SIMPLE", "SIMPLY",
        "SINGER", "SINGLE", "SISTER", "SIZZLE", "SKETCH", "SKEWER", "SLALOM",
        "SLEEVE", "SLEIGH", "SLIGHT", "SLOGAN", "SMILED", "SMOOTH", "SNATCH",
        "SNEEZE", "SNIPER", "SNOOZE", "SNORED", "SODIUM", "SOFTLY", "SOLDER",
        "SOLEMN", "SOLVED", "SONNET", "SOOTHE", "SORROW", "SOURCE", "SPARSE",
        "SPEECH", "SPHERE", "SPIDER", "SPIKED", "SPIRAL", "SPIRIT", "SPLASH",
        "SPLICE", "SPLINE", "SPOKEN", "SPONGE", "SPOOKY", "SPORTS", "SPRAIN",
        "SPRANG", "SPRAWL", "SPREAD", "SPRING", "SPRINT", "SPROUT", "SPRUCE",
        "SPYING", "SQUARE", "SQUASH", "SQUEAK", "SQUEAL", "SQUIRM", "STABLE",
        "STANCE", "STAPLE", "STARCH", "STARED", "STARRY", "STATIC", "STATUE",
        "STATUS", "STAYED", "STEADY", "STEAMY", "STENCH", "STEREO", "STICKY",
        "STIGMA", "STOLEN", "STORED", "STORMY", "STRAND", "STRAWS", "STREAK",
        "STREAM", "STREET", "STRESS", "STRIDE", "STRIKE", "STRING", "STRIPE",
        "STROKE", "STROLL", "STRONG", "STUCCO", "STUDIO", "STUFFY", "STUPID",
        "STYLUS", "SUBLET", "SUBMIT", "SUBTLE", "SUBWAY", "SUDDEN", "SUFFER",
        "SUGARY", "SUMMER", "SUMMIT", "SUNDAE", "SUNDAY", "SUNKEN", "SUNSET",
        "SUPPER", "SUPPLY", "SURELY", "SURVEY", "SWATCH", "SWIVEL", "SWORDS",
        "SYMBOL", "SYNTAX", "SYSTEM", "TABLET", "TACKLE", "TALENT", "TALKED",
        "TALKER", "TANDEM", "TANGLE", "TARGET", "TARIFF", "TASSEL", "TATTOO",
        "TAUGHT", "TAVERN", "TEAPOT", "TEASER", "TEDIUM", "TELLER", "TEMPER",
        "TEMPLE", "TENANT", "TENDER", "TENNIS", "TETHER", "THATCH", "THEORY",
        "THIRDS", "THIRST", "THIRTY", "THORNS", "THRASH", "THREAD", "THREAT",
        "THRESH", "THRICE", "THRIVE", "THRONE", "THRONG", "THROWN", "THRUST",
        "THUMBS", "THWART", "TICKET", "TICKLE", "TIDBIT", "TIGERS", "TIMBER",
        "TIMELY", "TINGLE", "TINKER", "TINSEL", "TIPTOE", "TISSUE", "TITLES",
        "TOFFEE", "TOGGLE", "TOMATO", "TONGUE", "TOPPLE", "TOSSED", "TOTALS",
        "TOUCAN", "TOUCHY", "TOWARD", "TOWELS", "TRACES", "TRACKS", "TRADED",
        "TRADER", "TRAGIC", "TRAILS", "TRAINS", "TRANCE", "TRAUMA", "TRAVEL",
        "TREATY", "TREBLE", "TREMOR", "TRENCH", "TRENDY", "TRIBES", "TRICKY",
        "TRIFLE", "TRIPLE", "TRIVIA", "TROPHY", "TROUGH", "TROWEL", "TRUCKS",
        "TRUDGE", "TRUSTY", "TUCKED", "TUMBLE", "TUNNEL", "TURBAN", "TURKEY",
        "TURNIP", "TURRET", "TURTLE", "TUSSLE", "TUXEDO", "TWELVE", "TWENTY",
        "TYCOON", "TYPING", "TYRANT", "UMPIRE", "UNABLE", "UNBOLT", "UNCLES",
        "UNCOIL", "UNCOOL", "UNDONE", "UNDULY", "UNEASY", "UNEVEN", "UNFAIR",
        "UNFOLD", "UNHOOK", "UNIQUE", "UNISON", "UNITED", "UNLESS", "UNLIKE",
        "UNLOAD", "UNLOCK", "UNMASK", "UNPACK", "UNPLUG", "UNREAL", "UNROLL",
        "UNRULY", "UNSAFE", "UNSEEN", "UNTOLD", "UNTRUE", "UNVEIL", "UNWIND",
        "UNWISE", "UPDATE", "UPHILL", "UPHOLD", "UPKEEP", "UPLAND", "UPLIFT",
        "UPLOAD", "UPROAR", "UPROOT", "UPSIDE", "UPTAKE", "UPTOWN", "UPWARD",
        "URCHIN", "URGENT", "USABLE", "USEFUL", "VACANT", "VACUUM", "VALLEY",
        "VALUED", "VALUES", "VALVES", "VANISH", "VANITY", "VARIED", "VASSAL",
        "VASTLY", "VECTOR", "VELLUM", "VELVET", "VENDOR", "VENEER", "VENOUS",
        "VENTED", "VENUES", "VERBAL", "VERIFY", "VERSES", "VESSEL", "VICTIM",
        "VICTOR", "VIEWER", "VINYLS", "VIOLET", "VIOLIN", "VIRTUE", "VISION",
        "VISUAL", "VOLLEY", "VOLUME", "VORTEX", "VOTERS", "VOTING", "VOWELS",
        "VOYAGE", "WADDLE", "WAFFLE", "WAGONS", "WAITED", "WAITER", "WAIVER",
        "WAKING", "WALKED", "WALKER", "WALLET", "WALLOW", "WALNUT", "WALRUS",
        "WANDER", "WARMER", "WARMLY", "WARMTH", "WARREN", "WASHED", "WASHER",
        "WATERY", "WATTLE", "WEAKEN", "WEAKLY", "WEALTH", "WEASEL", "WEAVER",
        "WEBBED", "WEDDED", "WEEDED", "WEEKLY", "WEIGHT", "WEIRDO", "WELDED",
        "WHALER", "WHEELS", "WHENCE", "WHIMSY", "WHINNY", "WHISKY", "WHITEN",
        "WHOLLY", "WICKER", "WIDELY", "WIDGET", "WIDTHS", "WIENER", "WIGGLE",
        "WILLOW", "WINDOW", "WINERY", "WINGED", "WINKED", "WINNER", "WINTER",
        "WIPERS", "WISDOM", "WISELY", "WISHED", "WITHIN", "WIZARD", "WOBBLE",
        "WONDER", "WOODEN", "WOOLEN", "WORKED", "WORKER", "WORMED", "WORTHY",
        "WRENCH", "WRETCH", "WRITER", "YAMMER", "YEARLY", "YELLED", "YELLOW",
        "YEOMAN", "YIPPEE", "YOGURT", "YONDER", "ZEALOT", "ZENITH", "ZEPHYR",
        "ZIGZAG", "ZINNIA", "ZODIAC", "ZOMBIE", "ZONKED",
    ],
}

# Guarantee every entry is exactly the right length, alphabetic, deduped.
# If a typo ever slips a wrong-length word in, it is silently dropped here
# rather than corrupting a puzzle.
WORDS = {
    n: sorted({w for w in ws if len(w) == n and w.isalpha() and w.isupper()})
    for n, ws in WORDS.items()
}

WORD_SETS = {n: set(ws) for n, ws in WORDS.items()}
